version: '3.8'

services:
  client:
    build: ./client/shopping-client
    ports:
      - "5173:80"
    depends_on:
      - server

  server-node:
    build: ./server-node
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://libigan:mySecure12356FR@cluster0.a6ywtxf.mongodb.net/shopping-app?retryWrites=true&w=majority
    # env_file:
    #   - ./server-node/.env

  server-dotnet:
    build: ./server-dotnet/ShoppingApi
    ports:
      - "5166:5166"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ShoppingDb;User=sa;Password=YourStrong!Passw0rd;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
